"use client";

/**
 * Community Engagement.
 *
 * Three tabs: Reddit (auto-scan), Quora (curated launcher + paste-question),
 * Avvo (curated launcher + paste-question). Suggested responses are
 * generated by Claude using the firm's brand voice and platform-specific
 * posting etiquette.
 */

import { useEffect, useMemo, useState } from "react";
import {
  DashCard,
  DashButton,
  DashSpinner,
  DashPill,
} from "@/components/dashboard-ui";

type Platform = "reddit" | "quora" | "avvo";

type ScanPost = {
  id: string;
  title: string;
  snippet: string;
  url: string;
  subreddit: string;
  author: string;
  created: number;
  relevanceScore: number;
  matchedKeywords: string[];
};

type ScanResult = {
  posts: ScanPost[];
  subredditsScanned: string[];
  totalFound: number;
  scannedAt: string;
};

function timeAgo(ts: number): string {
  const seconds = Math.floor(Date.now() / 1000 - ts);
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  return `${Math.floor(seconds / 86400)}d ago`;
}

function relevanceTone(s: number): "emerald" | "amber" | "blue" {
  if (s >= 60) return "emerald";
  if (s >= 30) return "amber";
  return "blue";
}

function relevanceLabel(s: number): string {
  if (s >= 60) return "High match";
  if (s >= 30) return "Medium match";
  return "Low match";
}

export default function CommunityPage() {
  const [platform, setPlatform] = useState<Platform>("reddit");

  return (
    <div className="px-4 py-8 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold tracking-tight">Community engagement</h1>
        <p className="text-sm text-slate-600 mt-1 max-w-2xl">
          Find employment-law discussions and draft helpful responses across
          Reddit, Quora, and Avvo. Suggested replies use Claude + the firm's
          brand voice and follow each platform's posting etiquette.
        </p>
      </div>

      <div className="flex gap-1 border-b border-slate-200 mb-6">
        {[
          { id: "reddit", label: "Reddit" },
          { id: "quora", label: "Quora" },
          { id: "avvo", label: "Avvo" },
        ].map((t) => (
          <button
            key={t.id}
            onClick={() => setPlatform(t.id as Platform)}
            className={`px-3 py-2 text-sm font-medium border-b-2 -mb-[1px] ${
              platform === t.id
                ? "border-[#185FA5] text-[#185FA5]"
                : "border-transparent text-slate-600 hover:text-slate-900"
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {platform === "reddit" && <RedditTab />}
      {(platform === "quora" || platform === "avvo") && <PasteTab platform={platform} />}
    </div>
  );
}

function RedditTab() {
  const [scan, setScan] = useState<ScanResult | null>(null);
  const [scanning, setScanning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<"all" | "high" | "medium">("all");

  const runScan = async () => {
    setScanning(true);
    setError(null);
    try {
      const res = await fetch("/api/community/reddit/scan");
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || "Scan failed");
      setScan(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Scan failed");
    } finally {
      setScanning(false);
    }
  };

  const filtered = useMemo(() => {
    if (!scan) return [];
    if (filter === "high") return scan.posts.filter((p) => p.relevanceScore >= 60);
    if (filter === "medium") return scan.posts.filter((p) => p.relevanceScore >= 30);
    return scan.posts;
  }, [scan, filter]);

  const high = scan?.posts.filter((p) => p.relevanceScore >= 60).length ?? 0;
  const med = scan?.posts.filter((p) => p.relevanceScore >= 30 && p.relevanceScore < 60).length ?? 0;

  if (!scan && !scanning) {
    return (
      <DashCard className="text-center py-10 space-y-3">
        <div className="text-3xl" aria-hidden>
          🔎
        </div>
        <h3 className="text-lg font-semibold">Scan Reddit for employment-law discussions</h3>
        <p className="text-sm text-slate-600 max-w-md mx-auto">
          Pulls recent posts from 11 employment-law-relevant subreddits
          (r/legaladvice, r/AskHR, r/jobs, r/antiwork, r/nyc, r/newjersey,
          and more), scores each for relevance to a NY/NJ employment firm,
          and ranks the best ones to engage with.
        </p>
        <DashButton onClick={runScan}>Start scan</DashButton>
        {error && <p className="text-sm text-red-700 mt-2">{error}</p>}
      </DashCard>
    );
  }

  if (scanning && !scan) {
    return (
      <DashCard className="text-center py-12">
        <DashSpinner /> Scanning subreddits…
        <p className="text-xs text-slate-500 mt-2">~15-30 seconds</p>
      </DashCard>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs text-slate-500">Filter:</span>
          {(["all", "high", "medium"] as const).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`text-xs px-2 py-1 rounded-full border ${
                filter === f
                  ? "border-[#185FA5] text-[#185FA5] bg-[#185FA5]/5"
                  : "border-slate-200 text-slate-600 hover:border-slate-400"
              }`}
            >
              {f === "all" ? "All" : f === "high" ? "High match" : "Medium+"}
            </button>
          ))}
          <span className="text-xs text-slate-500 ml-2">
            Showing {filtered.length} of {scan?.posts.length ?? 0}
          </span>
        </div>
        <button
          onClick={runScan}
          disabled={scanning}
          className="text-xs px-3 py-1.5 rounded-md border border-slate-300 hover:border-[#185FA5] hover:text-[#185FA5] disabled:opacity-50"
        >
          {scanning ? "Rescanning…" : "Rescan"}
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Stat label="Total found" value={scan?.posts.length ?? 0} />
        <Stat label="High relevance" value={high} tone="emerald" />
        <Stat label="Medium relevance" value={med} tone="amber" />
        <Stat label="Subreddits scanned" value={scan?.subredditsScanned.length ?? 0} />
      </div>

      <div className="space-y-3">
        {filtered.map((p) => (
          <PostCard key={p.id} post={p} />
        ))}
      </div>
    </div>
  );
}

function PostCard({ post }: { post: ScanPost }) {
  const [expanded, setExpanded] = useState(false);
  const [suggestion, setSuggestion] = useState<{ text: string; warning: string } | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showSuggestion, setShowSuggestion] = useState(false);

  const fetchSuggestion = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/community/suggest", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          platform: "reddit",
          title: post.title,
          body: post.snippet,
        }),
      });
      const data = await res.json();
      if (res.ok) {
        setSuggestion({ text: data.text, warning: data.warning });
        setShowSuggestion(true);
      }
    } finally {
      setLoading(false);
    }
  };

  const copy = async () => {
    if (!suggestion) return;
    await navigator.clipboard.writeText(suggestion.text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <DashCard>
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap mb-1.5">
            <DashPill tone="amber">r/{post.subreddit}</DashPill>
            <DashPill tone={relevanceTone(post.relevanceScore)}>
              {relevanceLabel(post.relevanceScore)} · {post.relevanceScore}
            </DashPill>
            <span className="text-xs text-slate-500">{timeAgo(post.created)}</span>
            <span className="text-xs text-slate-500">u/{post.author}</span>
          </div>
          <a
            href={post.url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-sm font-semibold text-slate-900 hover:text-[#185FA5] hover:underline"
          >
            {post.title}
          </a>
        </div>
        <a
          href={post.url}
          target="_blank"
          rel="noopener noreferrer"
          className="text-xs px-2 py-1 rounded border border-slate-300 hover:border-[#185FA5] hover:text-[#185FA5] shrink-0"
        >
          ↗ Open
        </a>
      </div>

      {post.snippet && (
        <div className="mt-2">
          <p className={`text-xs text-slate-600 ${expanded ? "" : "line-clamp-2"}`}>
            {post.snippet}
          </p>
          {post.snippet.length > 150 && (
            <button
              onClick={() => setExpanded((e) => !e)}
              className="text-xs text-[#185FA5] hover:underline mt-1"
            >
              {expanded ? "Show less" : "Read more"}
            </button>
          )}
        </div>
      )}

      {post.matchedKeywords.length > 0 && (
        <div className="flex flex-wrap gap-1 mt-2">
          {post.matchedKeywords.map((k, i) => (
            <span
              key={i}
              className="text-[10px] px-1.5 py-0.5 rounded bg-slate-50 text-slate-600 border border-slate-200"
            >
              {k}
            </span>
          ))}
        </div>
      )}

      <div className="mt-3 flex items-center gap-2 flex-wrap">
        {!suggestion ? (
          <DashButton variant="outline" onClick={fetchSuggestion} disabled={loading}>
            {loading ? <DashSpinner /> : "✦ Draft response"}
          </DashButton>
        ) : (
          <button
            onClick={() => setShowSuggestion((s) => !s)}
            className="text-xs px-3 py-1.5 rounded-md border border-[#185FA5] text-[#185FA5]"
          >
            {showSuggestion ? "Hide draft" : "Show draft"}
          </button>
        )}
      </div>

      {showSuggestion && suggestion && (
        <div className="mt-3 border-t border-slate-200 pt-3">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-medium text-[#185FA5]">✦ Suggested response</span>
            <button
              onClick={copy}
              className="text-xs px-2 py-1 rounded border border-slate-300 hover:border-slate-400"
            >
              {copied ? "✓ Copied" : "Copy"}
            </button>
          </div>
          <div className="text-xs text-slate-700 whitespace-pre-wrap leading-relaxed bg-slate-50 rounded-md p-3">
            {suggestion.text}
          </div>
          <div className="mt-2 text-[11px] text-amber-800 bg-amber-50 border border-amber-200 rounded-md px-2 py-1">
            ⚠ {suggestion.warning}
          </div>
        </div>
      )}
    </DashCard>
  );
}

function PasteTab({ platform }: { platform: Platform }) {
  const [links, setLinks] = useState<{ label: string; url: string }[]>([]);
  const [text, setText] = useState("");
  const [generating, setGenerating] = useState(false);
  const [response, setResponse] = useState<{ text: string; warning: string } | null>(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(`/api/community/links?platform=${platform}`)
      .then((r) => r.json())
      .then((d) => setLinks(d.links ?? []))
      .catch(() => setLinks([]));
  }, [platform]);

  const generate = async () => {
    if (!text.trim()) return;
    setGenerating(true);
    setError(null);
    setResponse(null);
    try {
      const res = await fetch("/api/community/suggest", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ platform, title: text.trim() }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || "Generate failed");
      setResponse({ text: data.text, warning: data.warning });
    } catch (e) {
      setError(e instanceof Error ? e.message : "Generate failed");
    } finally {
      setGenerating(false);
    }
  };

  const copy = async () => {
    if (!response) return;
    await navigator.clipboard.writeText(response.text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const platformName = platform === "quora" ? "Quora" : "Avvo";

  return (
    <div className="space-y-4">
      <DashCard>
        <h3 className="text-sm font-semibold mb-2">Browse {platformName} topics</h3>
        <p className="text-xs text-slate-600 mb-3">
          {platformName} blocks automated scanning, so we can't scan it for you.
          Browse the topic pages below, find a worth-answering question, then
          paste it into the panel below for an AI-suggested response.
        </p>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
          {links.map((link) => (
            <a
              key={link.url}
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs px-3 py-2 rounded-md border border-slate-300 hover:border-[#185FA5] hover:text-[#185FA5] flex items-center justify-between"
            >
              <span className="truncate">{link.label}</span>
              <span className="text-slate-400 text-xs">↗</span>
            </a>
          ))}
        </div>
      </DashCard>

      <DashCard>
        <h3 className="text-sm font-semibold mb-2">Draft a response</h3>
        <p className="text-xs text-slate-600 mb-3">
          Paste a {platformName} question and Claude will draft a reply in the
          firm's voice with proper {platformName} etiquette.
        </p>
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder={`Paste a ${platformName} question here…`}
          rows={6}
          className="w-full px-3 py-2 rounded-md border border-slate-300 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#185FA5]/30 focus:border-[#185FA5]"
        />
        <div className="mt-3 flex items-center gap-2">
          <DashButton onClick={generate} disabled={generating || !text.trim()}>
            {generating ? <DashSpinner /> : "✦ Generate response"}
          </DashButton>
          {text && (
            <button
              onClick={() => {
                setText("");
                setResponse(null);
                setError(null);
              }}
              className="text-xs text-slate-500 hover:text-slate-900"
            >
              Clear
            </button>
          )}
        </div>
        {error && <p className="text-sm text-red-700 mt-2">{error}</p>}
      </DashCard>

      {response && (
        <DashCard>
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium text-[#185FA5]">
              ✦ Suggested response for {platformName}
            </span>
            <button
              onClick={copy}
              className="text-xs px-2 py-1 rounded border border-slate-300 hover:border-slate-400"
            >
              {copied ? "✓ Copied" : "Copy"}
            </button>
          </div>
          <div className="text-sm text-slate-700 whitespace-pre-wrap leading-relaxed bg-slate-50 rounded-md p-4 border border-slate-200">
            {response.text}
          </div>
          <div className="mt-3 text-xs text-amber-800 bg-amber-50 border border-amber-200 rounded-md px-3 py-2">
            ⚠ {response.warning}
          </div>
        </DashCard>
      )}
    </div>
  );
}

function Stat({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone?: "emerald" | "amber";
}) {
  const color =
    tone === "emerald" ? "text-emerald-700" : tone === "amber" ? "text-amber-700" : "text-slate-900";
  return (
    <div className="border border-slate-200 rounded-lg p-3 bg-white">
      <div className={`text-2xl font-bold ${color}`}>{value}</div>
      <div className="text-xs text-slate-500 mt-1">{label}</div>
    </div>
  );
}
