"use client";

/**
 * State Rules — per-jurisdiction attorney-advertising rules that drive the ad
 * compliance checker. Can be AI-seeded for all 50 states + DC, then verified.
 *
 * Lives under Content Standards (/brand-voice). Backed by
 * /api/compliance/state-rules (CRUD) and /api/compliance/state-rules/seed (AI).
 */

import { useCallback, useEffect, useState } from "react";

import { US_JURISDICTIONS, US_JURISDICTION_NAME } from "@/lib/us-jurisdictions";

type KeyRule = { citation: string; rule: string; severity: "high" | "medium" | "low" };

type StateRule = {
  id: string;
  jurisdiction_code: string;
  jurisdiction_name: string;
  governing_authority: string | null;
  rules_summary: string | null;
  key_rules: KeyRule[];
  required_label: string | null;
  notes: string | null;
  enabled: boolean;
  review_status: string;
  last_verified_at: string | null;
  updated_at: string;
};

const REVIEW_STATUSES = ["unverified", "verified", "needs_review", "archived"];

const input =
  "mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 text-sm shadow-sm focus:border-slate-500 focus:outline-none focus:ring-1 focus:ring-slate-500";
const label = "block text-xs font-semibold text-slate-700";

function Pill({
  children,
  tone = "slate",
}: {
  children: React.ReactNode;
  tone?: "slate" | "green" | "amber" | "red";
}) {
  const tones: Record<string, string> = {
    slate: "border-slate-200 bg-slate-50 text-slate-600",
    green: "border-emerald-200 bg-emerald-50 text-emerald-700",
    amber: "border-amber-200 bg-amber-50 text-amber-700",
    red: "border-red-200 bg-red-50 text-red-700",
  };
  return <span className={`rounded-full border px-2 py-0.5 text-[10px] ${tones[tone]}`}>{children}</span>;
}

export default function StateRulesManager() {
  const [rows, setRows] = useState<StateRule[]>([]);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<Partial<StateRule> | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [seeding, setSeeding] = useState(false);
  const [seedMsg, setSeedMsg] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/compliance/state-rules", { cache: "no-store" });
      const json = await res.json();
      if (res.ok) setRows(json.rules ?? []);
    } finally {
      setLoading(false);
    }
  }, []);
  useEffect(() => {
    load();
  }, [load]);

  async function seed() {
    if (
      !confirm(
        "Generate AI-drafted advertising rules for every US jurisdiction not yet present? This can take a couple of minutes. All drafts land as 'unverified' for attorney review.",
      )
    )
      return;
    setSeeding(true);
    setSeedMsg(null);
    try {
      const res = await fetch("/api/compliance/state-rules/seed", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json?.error ?? "seed failed");
      setSeedMsg(
        `Added ${json.inserted} jurisdiction${json.inserted === 1 ? "" : "s"}` +
          (json.skipped ? ` (${json.skipped} already existed)` : "") +
          ". Review each before relying on it.",
      );
      load();
    } catch (e) {
      setSeedMsg(e instanceof Error ? e.message : "seed failed");
    } finally {
      setSeeding(false);
    }
  }

  async function save() {
    if (!editing?.jurisdiction_code || !editing?.jurisdiction_name) {
      setError("Jurisdiction is required.");
      return;
    }
    setError(null);
    const res = await fetch("/api/compliance/state-rules", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(editing),
    });
    const json = await res.json();
    if (!res.ok) {
      setError(json?.error ?? "save failed");
      return;
    }
    setEditing(null);
    load();
  }

  async function del(id: string) {
    if (!confirm("Delete this jurisdiction's rules?")) return;
    await fetch(`/api/compliance/state-rules?id=${id}`, { method: "DELETE" });
    load();
  }

  function setKeyRule(i: number, patch: Partial<KeyRule>) {
    if (!editing) return;
    const kr = [...(editing.key_rules ?? [])];
    kr[i] = { ...kr[i], ...patch } as KeyRule;
    setEditing({ ...editing, key_rules: kr });
  }

  return (
    <div>
      <div className="mb-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-xs text-amber-900">
        <strong>AI-drafted — not legal advice.</strong> Seeded rules are a
        starting point generated by AI. Every rule must be verified by counsel
        before you rely on it. Mark a jurisdiction <em>verified</em> once
        reviewed.
      </div>

      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-slate-600">
          {rows.length} jurisdiction{rows.length === 1 ? "" : "s"} of{" "}
          {US_JURISDICTIONS.length}. These rules drive the ad compliance checker
          on the Ads page.
        </p>
        <div className="flex gap-2">
          <button
            onClick={seed}
            disabled={seeding}
            className="rounded-md border border-slate-300 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          >
            {seeding ? "Generating… (1-3 min)" : "Generate / refresh state rules"}
          </button>
          <button
            onClick={() =>
              setEditing({
                key_rules: [],
                enabled: true,
                review_status: "unverified",
              })
            }
            className="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-800"
          >
            + Add jurisdiction
          </button>
        </div>
      </div>
      {seedMsg && <p className="mb-4 text-sm text-slate-700">{seedMsg}</p>}

      {editing && (
        <div className="mb-5 rounded-lg border border-slate-300 bg-slate-50 p-4">
          <div className="grid gap-3 sm:grid-cols-2">
            <div>
              <label className={label}>Jurisdiction *</label>
              <select
                className={input}
                value={editing.jurisdiction_code ?? ""}
                onChange={(e) =>
                  setEditing({
                    ...editing,
                    jurisdiction_code: e.target.value,
                    jurisdiction_name: US_JURISDICTION_NAME[e.target.value] ?? "",
                  })
                }
              >
                <option value="">Select…</option>
                {US_JURISDICTIONS.map((j) => (
                  <option key={j.code} value={j.code}>
                    {j.name} ({j.code})
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className={label}>Required label / disclosure</label>
              <input
                className={input}
                value={editing.required_label ?? ""}
                onChange={(e) => setEditing({ ...editing, required_label: e.target.value })}
                placeholder="Attorney Advertising"
              />
            </div>
            <div className="sm:col-span-2">
              <label className={label}>Governing authority</label>
              <input
                className={input}
                value={editing.governing_authority ?? ""}
                onChange={(e) => setEditing({ ...editing, governing_authority: e.target.value })}
                placeholder="California Rules of Professional Conduct, Rule 7.1-7.5"
              />
            </div>
            <div className="sm:col-span-2">
              <label className={label}>Rules summary (injected into the compliance prompt)</label>
              <textarea
                className={input}
                rows={5}
                value={editing.rules_summary ?? ""}
                onChange={(e) => setEditing({ ...editing, rules_summary: e.target.value })}
              />
            </div>

            <div className="sm:col-span-2">
              <label className={label}>Key rules</label>
              <div className="mt-1 space-y-2">
                {(editing.key_rules ?? []).map((k, i) => (
                  <div key={i} className="flex flex-wrap items-center gap-2">
                    <input
                      className="w-32 rounded-md border border-slate-300 px-2 py-1 text-xs"
                      value={k.citation}
                      onChange={(e) => setKeyRule(i, { citation: e.target.value })}
                      placeholder="RPC 7.1(a)"
                    />
                    <input
                      className="min-w-[220px] flex-1 rounded-md border border-slate-300 px-2 py-1 text-xs"
                      value={k.rule}
                      onChange={(e) => setKeyRule(i, { rule: e.target.value })}
                      placeholder="No false or misleading statements…"
                    />
                    <select
                      className="rounded-md border border-slate-300 px-2 py-1 text-xs"
                      value={k.severity}
                      onChange={(e) =>
                        setKeyRule(i, { severity: e.target.value as KeyRule["severity"] })
                      }
                    >
                      {["high", "medium", "low"].map((s) => (
                        <option key={s} value={s}>
                          {s}
                        </option>
                      ))}
                    </select>
                    <button
                      onClick={() =>
                        setEditing({
                          ...editing,
                          key_rules: (editing.key_rules ?? []).filter((_, j) => j !== i),
                        })
                      }
                      className="text-xs text-red-700 hover:underline"
                    >
                      Remove
                    </button>
                  </div>
                ))}
                <button
                  onClick={() =>
                    setEditing({
                      ...editing,
                      key_rules: [
                        ...(editing.key_rules ?? []),
                        { citation: "", rule: "", severity: "medium" },
                      ],
                    })
                  }
                  className="text-xs font-medium text-slate-700 hover:underline"
                >
                  + Add rule
                </button>
              </div>
            </div>

            <div>
              <label className={label}>Review status</label>
              <select
                className={input}
                value={editing.review_status ?? "unverified"}
                onChange={(e) => setEditing({ ...editing, review_status: e.target.value })}
              >
                {REVIEW_STATUSES.map((t) => (
                  <option key={t} value={t}>
                    {t}
                  </option>
                ))}
              </select>
            </div>
            <div className="flex items-end">
              <label className="flex items-center gap-2 text-sm text-slate-700">
                <input
                  type="checkbox"
                  checked={editing.enabled ?? true}
                  onChange={(e) => setEditing({ ...editing, enabled: e.target.checked })}
                />
                Enabled (used by the checker)
              </label>
            </div>
            <div className="sm:col-span-2">
              <label className={label}>Notes</label>
              <textarea
                className={input}
                rows={2}
                value={editing.notes ?? ""}
                onChange={(e) => setEditing({ ...editing, notes: e.target.value })}
              />
            </div>
          </div>
          {error && <p className="mt-2 text-sm text-red-700">{error}</p>}
          <div className="mt-3 flex gap-2">
            <button
              onClick={save}
              className="rounded-md bg-slate-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-slate-800"
            >
              Save
            </button>
            <button
              onClick={() => {
                setEditing(null);
                setError(null);
              }}
              className="rounded-md border border-slate-300 px-3 py-1.5 text-sm text-slate-700"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {loading ? (
        <p className="text-sm text-slate-500">Loading…</p>
      ) : rows.length === 0 ? (
        <p className="text-sm text-slate-500">
          No jurisdictions yet. Click <strong>Generate / refresh state rules</strong>{" "}
          to AI-draft all 50 states + DC, or add one manually.
        </p>
      ) : (
        <ul className="space-y-2">
          {rows.map((s) => (
            <li key={s.id} className="rounded-lg border border-slate-200 bg-white p-3 shadow-sm">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-medium text-slate-900">
                      {s.jurisdiction_name} ({s.jurisdiction_code})
                    </span>
                    <Pill tone={s.review_status === "verified" ? "green" : "amber"}>
                      {s.review_status}
                    </Pill>
                    {!s.enabled && <Pill tone="red">disabled</Pill>}
                    {s.required_label && <Pill>{s.required_label}</Pill>}
                  </div>
                  {s.governing_authority && (
                    <p className="mt-1 text-xs font-medium text-slate-600">
                      {s.governing_authority}
                    </p>
                  )}
                  {s.rules_summary && (
                    <p className="mt-1 line-clamp-3 text-xs text-slate-600">{s.rules_summary}</p>
                  )}
                  {s.key_rules.length > 0 && (
                    <p className="mt-1 text-[11px] text-slate-500">
                      {s.key_rules.length} key rule{s.key_rules.length === 1 ? "" : "s"}
                    </p>
                  )}
                </div>
                <div className="flex shrink-0 gap-2">
                  <button
                    onClick={() => setEditing(s)}
                    className="text-xs text-slate-600 hover:text-slate-900"
                  >
                    Edit
                  </button>
                  <button onClick={() => del(s.id)} className="text-xs text-red-700 hover:underline">
                    Delete
                  </button>
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
