/**
 * GET /api/social/calendar
 *
 * Feeds the Social Ops → Content Calendar screen. Reads the tenant's
 * social_posts (the table every scheduled/published post lands in, whether it
 * came from a blog splinter, a service-page post, or a manual marketing alert
 * pushed through the Ayrshare publish path) and returns a flat list the client
 * groups into the monthly grid and weekly time-slot views.
 *
 * Each item's calendar date is scheduled_at (for upcoming posts) falling back
 * to published_at, then created_at — so a post shows up on the day it is/was
 * meant to go live. Reads are RLS-scoped via getTenantDb.
 */

import { NextResponse } from "next/server";

import { guardUser } from "@/lib/supabase-route";
import { getTenantDb } from "@/lib/tenant-db";
import type { SocialChecklist, SocialSource } from "@/lib/content-social";
import type { PostMetrics } from "@/lib/ayrshare";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export type CalendarItem = {
  id: string;
  platform: string;
  body: string;
  status: string;
  /** The day this post is/was scheduled or published (ISO). */
  date: string;
  postUrl: string | null;
  sourceDraftId: string | null;
  /** Why a failed post was rejected (null unless status = failed). */
  lastError: string | null;
  /** Whether this post carries media (e.g. a carousel) — informs the editor. */
  hasMedia: boolean;
  /** Source tag the dedicated social generator stored on the draft (Rule 1). */
  source: SocialSource | null;
  /** Advisory Rule-10 checklist from the draft, when generated by the social generator. */
  checklist: SocialChecklist | null;
  /** Per-post performance (Phase 4). Null until the post is live and refreshed. */
  metrics: PostMetrics | null;
  metricsUpdatedAt: string | null;
};

function readSource(meta: Record<string, unknown>): SocialSource | null {
  const s = meta.social_source;
  return s && typeof s === "object" && "title" in s ? (s as SocialSource) : null;
}
function readChecklist(meta: Record<string, unknown>): SocialChecklist | null {
  const c = meta.social_checklist;
  return c && typeof c === "object" && "withinCaps" in c ? (c as SocialChecklist) : null;
}

export async function GET() {
  const denied = await guardUser();
  if (denied) return denied;

  const db = await getTenantDb();

  const cols =
    "id, platform, content, status, scheduled_at, posted_at, published_at, created_at, post_url, source_draft_id";
  // Progressive fallback so a missing OPTIONAL column doesn't drop the others:
  // metrics (newest) → last_error/media_urls → base columns. Without the tiers,
  // an un-migrated `metrics` column would also strip last_error + media_urls.
  let res = await db
    .from("social_posts")
    .select(`${cols}, last_error, media_urls, metrics, metrics_updated_at`)
    .order("created_at", { ascending: false })
    .limit(1000);
  if (res.error && /metrics/i.test(res.error.message)) {
    res = (await db
      .from("social_posts")
      .select(`${cols}, last_error, media_urls`)
      .order("created_at", { ascending: false })
      .limit(1000)) as typeof res;
  }
  if (res.error && /last_error|media_urls/i.test(res.error.message)) {
    res = (await db
      .from("social_posts")
      .select(cols)
      .order("created_at", { ascending: false })
      .limit(1000)) as typeof res;
  }
  const { data, error } = res;

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  const rows = (data ?? []) as Array<Record<string, unknown>>;
  const items: CalendarItem[] = rows
    .map((r) => {
      const date =
        (r.scheduled_at as string | null) ??
        (r.published_at as string | null) ??
        (r.posted_at as string | null) ??
        (r.created_at as string | null);
      if (!date) return null;
      const media = r.media_urls;
      return {
        id: String(r.id ?? ""),
        platform: String(r.platform ?? "").toLowerCase(),
        body: typeof r.content === "string" ? r.content : "",
        status: String(r.status ?? "published"),
        date,
        postUrl: (r.post_url as string | null) ?? null,
        sourceDraftId: (r.source_draft_id as string | null) ?? null,
        lastError: (r.last_error as string | null) ?? null,
        hasMedia: Array.isArray(media) && media.length > 0,
        source: null as SocialSource | null,
        checklist: null as SocialChecklist | null,
        metrics: (r.metrics as PostMetrics | null) ?? null,
        metricsUpdatedAt: (r.metrics_updated_at as string | null) ?? null,
      } satisfies CalendarItem;
    })
    .filter((x): x is CalendarItem => x !== null);

  // Attach the source tag + advisory checklist from the linked draft, so a
  // scheduled post carries the same Rule-1/Rule-10 context the review drawer
  // showed. Only posts generated by the dedicated social generator have them.
  const draftIds = [...new Set(items.map((i) => i.sourceDraftId).filter(Boolean))] as string[];
  if (draftIds.length) {
    const { data: drafts } = await db
      .from("content_drafts")
      .select("id, metadata")
      .in("id", draftIds);
    const byId = new Map<string, { source: SocialSource | null; checklist: SocialChecklist | null }>();
    for (const d of (drafts ?? []) as Array<Record<string, unknown>>) {
      const meta = (d.metadata ?? {}) as Record<string, unknown>;
      byId.set(String(d.id), { source: readSource(meta), checklist: readChecklist(meta) });
    }
    for (const it of items) {
      const m = it.sourceDraftId ? byId.get(it.sourceDraftId) : null;
      if (m) {
        it.source = m.source;
        it.checklist = m.checklist;
      }
    }
  }

  return NextResponse.json({ items });
}
