/**
 * Diana's Oct 6 2026 spec, Task 4: the new known traps, with the corrections
 * Kenneth approved on 2026-10-06. This file is the SOURCE: the SQL is generated
 * from it (scripts/emit-known-traps-oct6-sql.ts) and the tests read it
 * (scripts/check-known-traps-oct6.ts), so the tested pattern and the stored
 * pattern cannot drift apart.
 *
 * Changes from the spec as written, and why:
 *   5   Flagged Kenneth's own locked disclaimer ("For more information see our
 *       full" is his wording). Now flags a closing disclaimer that is NOT his
 *       exact first sentence.
 *   15  "something new" matched ordinary prose; narrowed to the consideration
 *       sense.
 *   24  "our client" in any sentence was critical, and Trap 7 now asks for
 *       first person ("our clients"), so it would have fired on most pages.
 *       Narrowed to a sentence that reports a result.
 *   27  "free consultation" is allowed (Kenneth, 2026-10-06); "contingen" also
 *       matched "contingent on"; the cost question must be about a lawyer.
 *   27es  "consulta gratuita" is allowed for the same reason.
 *   31  Critical in the spec, but Appendix D gives civil litigation pages no
 *       author, so a critical "missing byline" could never be cleared there.
 *       Important instead; Fix known errors adds the byline wherever an author
 *       is mapped.
 *   Spec "warning" is this system's "important".
 *
 * Pure data, no IO.
 */
import type { KnownTrap } from "./known-traps";

export type TrapSeed = Omit<KnownTrap, "id" | "enabled"> & { number: string };

const LOCKED_FIRST_SENTENCE = "is not legal advice and does not create an attorney client relationship";

export const OCT6_TRAPS: TrapSeed[] = [
  {
    number: "1",
    label: "New York described as recognizing a common law public policy exception",
    matchType: "all_of_unless",
    matchOn: "sentences",
    pattern: JSON.stringify(["public policy exception", "New York"]),
    unless: ["do not recognize", "does not recognize", "generally do not", "declined", "refused", "rejected", "unlike New York", "but not New York"],
    severity: "critical",
    note: "New York courts do not recognize a common law public policy exception to at will employment (Murphy v. American Home Products Corp., 58 N.Y.2d 293 (1983); Sabetay v. Sterling Drug, Inc., 69 N.Y.2d 329 (1987)). New Jersey does (Pierce v. Ortho Pharmaceutical Corp., 84 N.J. 58 (1980)).",
  },
  {
    number: "2",
    label: "Sabetay cited as support for a New York public policy exception",
    matchType: "all_of_unless",
    matchOn: "sentences",
    pattern: JSON.stringify(["Sabetay"]),
    unless: ["declined", "refused", "rejected", "do not recognize", "does not recognize"],
    severity: "critical",
    note: "Sabetay v. Sterling Drug (1987) rejected a public policy exception in New York.",
  },
  {
    number: "2b",
    label: "Wieder cited as a general illegal acts exception",
    matchType: "all_of_unless",
    matchOn: "sentences",
    pattern: JSON.stringify(["Wieder"]),
    unless: ["law firm", "lawyers employed by"],
    severity: "critical",
    note: "Wieder v. Skala (1992) recognized only a narrow implied term for lawyers employed by law firms.",
  },
  {
    number: "3",
    label: "Labor Law 740 described with the pre 2022 substantial danger requirement",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`\b(?:violation|it|the\s+conduct)\s+must\s+(?:create|present|pose)\s+a\s+substantial(?:\s+and\s+specific)?\s+danger\b`,
    unless: [],
    severity: "critical",
    note: "Since January 26, 2022, NY Labor Law 740 covers conduct the employee reasonably believes violates a law, rule or regulation, or poses a substantial and specific danger to public health or safety.",
  },
  {
    number: "4",
    label: "New York pay changes described as allowed without notice",
    matchType: "document",
    pattern: JSON.stringify(["without notice", "pay"]),
    unless: ["seven calendar days", "7 calendar days", "195"],
    severity: "critical",
    note: "NY Labor Law 195(2): written notice of a pay rate change at least seven calendar days before it takes effect, unless shown on the wage statement.",
  },
  {
    number: "5",
    label: "Reworded closing disclaimer",
    matchType: "regex",
    matchOn: "sentences",
    appliesTo: "web",
    pattern: String.raw`general informational purposes only`,
    unless: [LOCKED_FIRST_SENTENCE],
    severity: "critical",
    note: "Only the locked disclaimer is allowed (Kenneth, 2026-09-29): \"This article is for general informational purposes only, is not legal advice and does not create an attorney client relationship. For more information see our full Disclaimer.\" Fix known errors replaces any other wording.",
  },
  {
    number: "6",
    label: "CTA repeated inside one line",
    matchType: "regex",
    matchOn: "raw_body",
    appliesTo: "web",
    pattern: String.raw`Call today at[^\n]*Call today at`,
    unless: [],
    severity: "critical",
    note: "The CTA was inserted inside itself. Fix known errors rebuilds the ending with one CTA.",
  },
  {
    number: "7",
    label: "Firm described in the third person",
    matchType: "regex",
    matchOn: "sentences",
    appliesTo: "web",
    pattern: String.raw`\b(?:The firm|Katz Melinger PLLC|Katz Melinger)\s+(?:represents|handles|offers|helps|works|provides|focuses)\b`,
    unless: [],
    severity: "important",
    note: "Blogs and service pages are written as \"we\" and \"our firm\" (Diana, October 6, 2026). Rewrite the sentence in the first person: \"we represent\", not \"The firm represents\".",
  },
  {
    number: "8",
    label: "Hyphenated compound word",
    matchType: "regex",
    matchOn: "sentences",
    appliesTo: "web",
    caseSensitive: true,
    pattern: String.raw`\b[a-z]+-[a-z]+\b`,
    unless: ["Sarbanes-Oxley", "Dodd-Frank", "http"],
    severity: "important",
    note: "No hyphens except phone numbers, statute numbers and official law names. Replace the hyphen with a space.",
  },
  {
    number: "9",
    label: "NYCHRL harassment coverage stated as four or more",
    matchType: "all_of_unless",
    matchOn: "sentences",
    scope: "title_or_keyword_contains:harass",
    pattern: JSON.stringify(["City Human Rights Law", "four or more"]),
    unless: ["any size", "harassment claims apply"],
    severity: "important",
    note: "For sexual and gender based harassment the NYCHRL covers employers of any size.",
  },
  {
    number: "10",
    label: "NYC Commission one year in harassment content",
    matchType: "regex",
    matchOn: "sentences",
    scope: "title_or_keyword_contains:harass",
    pattern: String.raw`Commission on Human Rights[^.\n]{0,80}\b(?:1|one)\s+year`,
    unless: ["gender based harassment", "three years for"],
    severity: "important",
    note: "The NYC Commission allows three years for gender based harassment complaints.",
  },
  {
    number: "11",
    label: "Harassment settlement confidentiality described as routine",
    matchType: "all_of_unless",
    matchOn: "sentences",
    pattern: JSON.stringify(["settlement", "confidentiality"]),
    unless: ["5-336", "preference", "10:5-12.8", "limits", "ruling", "prevent"],
    severity: "critical",
    note: "NY GOL 5-336 allows confidentiality only at the employee's preference, with time to consider and 7 days to revoke; N.J.S.A. 10:5-12.8 bars terms concealing discrimination, harassment or retaliation details.",
  },
  {
    number: "12",
    label: "No review period for employees under 40",
    matchType: "all_of_unless",
    matchOn: "sentences",
    pattern: JSON.stringify(["under 40"]),
    unless: ["5-336", "federal law does not set", "no federal law sets"],
    severity: "important",
    note: "Mention NY GOL 5-336 when confidentiality about a discrimination, harassment or retaliation claim is included.",
  },
  {
    number: "13",
    label: "OWBPA overstated",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`makes the release unenforceable|cannot shorten these timeframes`,
    unless: [],
    severity: "important",
    note: "The employee may sign early; a missing OWBPA period invalidates only the age claim waiver.",
  },
  {
    number: "14",
    label: "FLSA claims described as released by a private agreement",
    matchType: "all_of_unless",
    matchOn: "sentences",
    pattern: JSON.stringify(["release", "Fair Labor Standards Act"]),
    unless: ["court", "Department of Labor", "approval"],
    severity: "critical",
    note: "FLSA claims generally cannot be released privately without court or DOL approval.",
  },
  {
    number: "15",
    label: "Non compete requires new consideration",
    matchType: "regex",
    matchOn: "sentences",
    // A REQUIREMENT of new consideration, not the words: "a new consideration
    // on your mind" and "the severance serves as new consideration" are fine.
    pattern: String.raw`\b(?:requires?|required|must|needs?|need to|has to|have to)\b[^.\n]{0,80}\b(?:new|additional|real|fresh|separate) consideration\b|\bmust (?:receive|be given|get) something\b|\b(?:must|need to|have to) (?:have )?(?:give|given|receive|received|get|got)(?: you)? something new\b`,
    unless: ["continued employment"],
    severity: "critical",
    note: "In NY and NJ, continued employment is generally enough consideration for a non compete.",
  },
  {
    number: "16",
    label: "FTC non compete rule status out of date",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`(?:FTC|Federal Trade Commission)[^.\n]{0,100}non.?compete`,
    unless: ["2025", "dropped its appeals", "no federal ban", "website", "read more"],
    severity: "important",
    note: "A federal court set the FTC rule aside in 2024 and the FTC dropped its appeals in September 2025; there is no federal ban.",
  },
  {
    number: "17",
    label: "Restraining notice amount",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`(?:freez|restrain)[^.\n]{0,80}amount of the judgment`,
    unless: ["twice"],
    severity: "critical",
    note: "CPLR 5222(b): a restraining notice covers up to twice the amount of the judgment.",
  },
  {
    number: "18",
    label: "New Jersey Special Civil Part limit",
    matchType: "all_of_unless",
    matchOn: "sentences",
    pattern: JSON.stringify(["Special Civil Part", "15,000"]),
    unless: ["20,000"],
    severity: "critical",
    note: "The NJ Special Civil Part limit is $20,000 since July 1, 2022.",
  },
  {
    number: "19",
    label: "Court limit stated in years",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`jurisdictional (?:minimum|limit)[^.\n]{0,60}\b\d+\s+years`,
    unless: [],
    severity: "critical",
    note: "A dollar figure was replaced with a time period.",
  },
  {
    number: "20",
    label: "FDCPA applied to all collection agencies",
    matchType: "all_of_unless",
    matchOn: "sentences",
    pattern: JSON.stringify(["Fair Debt Collection Practices Act", "collection agenc"]),
    unless: ["consumer"],
    severity: "important",
    note: "The FDCPA covers consumer debts only.",
  },
  {
    number: "21",
    label: "Unsourced weeks of pay statistic",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`\b(?:one|two|three|\d+)\s+(?:to|or)\s+(?:two|three|four|\d+)\s+weeks of pay`,
    unless: [],
    severity: "important",
    note: "Statistics need a linked source or must be removed.",
  },
  {
    number: "22",
    label: "Unfulfilled quid pro quo threat without federal caveat",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`quid pro quo[^.\n]*(?:does not follow|never loses)|(?:does not follow|never loses)[^.\n]*quid pro quo`,
    unless: ["hostile work environment", "?"],
    severity: "important",
    note: "Under federal law an unfulfilled threat is usually analyzed as a hostile work environment claim.",
  },
  {
    number: "23",
    label: "Names not on the approved people list",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`Seth Katz|Craig Melinger|Daniel Melinger`,
    unless: [],
    severity: "critical",
    note: "Approved people: Kenneth Katz, Nicole Grunfeld, Adam Sackowitz.",
  },
  {
    number: "24",
    label: "Client result without the prior results line",
    matchType: "document",
    appliesTo: "web",
    pattern: String.raw`\bour clients?\b[^.\n]{0,150}\b(?:recovered|secured|obtained|won|awarded|collected|settled for)\b|\b(?:recovered|secured|obtained|won|collected)\b[^.\n]{0,150}\bfor (?:our|a) clients?\b`,
    unless: ["Prior results do not guarantee"],
    severity: "critical",
    note: "A client result needs \"Prior results do not guarantee a similar outcome.\" after it.",
  },
  {
    number: "25",
    label: "Link with no destination",
    matchType: "regex",
    matchOn: "raw_body",
    appliesTo: "web",
    pattern: String.raw`\]\(#\)`,
    unless: [],
    severity: "critical",
    note: "A link points nowhere (#). Give it the real page or remove the link.",
  },
  {
    number: "26",
    label: "Developer or checklist block in the body",
    matchType: "regex",
    matchOn: "raw_body",
    appliesTo: "web",
    caseSensitive: true,
    pattern: String.raw`===\s*[A-Z ,]+===|REMOVE BEFORE PUBLISHING|FOR DEVELOPER|DEVELOPER NOTE`,
    unless: [],
    severity: "critical",
    note: "Internal notes must never be in the body. SEO fields belong in metadata.",
  },
  {
    number: "27",
    label: "Fee discussion",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`\bfee structures?\b|\bwhat (?:the|an) attorney charges\b|\bexplain their fees\b|\bHow much does[^?\n]*\b(?:lawyer|attorney)\b[^?\n]*\b(?:cost|charge)|\bcontingency\b|\bcontingent[\s-]fees?\b|\bno fee unless\b|\b(?:written )?fee agreements?\b|\bhow (?:fees|legal fees) (?:and costs )?are handled\b|\bno upfront\b|\bpay nothing unless\b`,
    unless: [],
    severity: "critical",
    note: "No statements about how lawyers charge or any payment arrangement. A free consultation or Free Confidential Case Evaluation may be offered (Kenneth, 2026-10-06).",
  },
  {
    number: "27es",
    label: "Fee discussion in Spanish",
    matchType: "regex",
    matchOn: "sentences",
    pattern: String.raw`honorarios contingentes|base de contingencia|no paga[^.\n]*a menos que|sin costo por adelantado|porcentaje de lo que recupere`,
    unless: [],
    severity: "critical",
    note: "Spanish fee rule. A free consultation may be offered; payment arrangements may not be described.",
  },
  {
    number: "28",
    label: "Citation broken by the state name rule",
    matchType: "regex",
    matchOn: "raw_body",
    appliesTo: "web",
    caseSensitive: true,
    pattern: String.raw`New York(?:C\.|\.2d|\.3d|\.S\.)|New Jersey\.(?:J\.|Super)|New York(?=C\b)`,
    unless: [],
    severity: "critical",
    note: "The state name rule expanded an abbreviation inside a citation (N.Y.C., N.Y.2d, N.J. Super.). Restore the citation.",
  },
  {
    number: "29",
    label: "Emoji in a blog or web page",
    matchType: "regex",
    matchOn: "raw_body",
    appliesTo: "web",
    regexFlags: "u",
    pattern: String.raw`[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]`,
    unless: [],
    severity: "important",
    note: "No emojis in blogs or web pages.",
  },
  {
    number: "30",
    label: "Extra or reworded disclaimer",
    matchType: "regex",
    matchOn: "sentences",
    appliesTo: "web",
    pattern: String.raw`does not constitute legal advice|contains general information`,
    unless: [],
    severity: "important",
    note: "Only the locked disclaimer may appear, once. Fix known errors removes the others.",
  },
  {
    number: "31",
    label: "Missing byline",
    matchType: "document_missing",
    appliesTo: "web",
    pattern: String.raw`^\s*[*_]*\s*By [A-Z]`,
    unless: [],
    severity: "important",
    note: "Website drafts carry \"By [author], Katz Melinger PLLC\" under the H1: Nicole Grunfeld for employment, Adam Sackowitz for commercial collections, Kenneth Katz for judgment enforcement. Fix known errors adds it where the practice area is mapped.",
  },
];
