/**
 * Social copy rulebook — hard length caps, hook formulas, and banned openers,
 * per format. This is the data + validation layer for the dedicated social
 * generator (lib/content-social.ts). It exists SO social copy is no longer
 * generated by the blog system with soft, unenforced length guidance.
 *
 * Caps mirror the social spec Rule 5 exactly. Each format carries:
 *   - promptRules: the instruction lines injected into the generator prompt
 *   - validate():   returns violation strings ([] = within caps)
 *   - trim():       best-effort clamp to bring output within caps (the floor
 *                   applied after a regeneration attempt still overflows)
 *
 * Formats reuse the existing FormatKey values so content_drafts.format and the
 * scheduler keep working. "video_short" is the TikTok/Reels (Craig LeVay) script.
 */

import { parseCarouselScript } from "./carousel-slides";

export type SocialFormatKey =
  | "carousel"
  | "linkedin"
  | "facebook"
  | "instagram"
  | "twitter"
  | "video_short";

export const SOCIAL_FORMAT_KEYS: SocialFormatKey[] = [
  "carousel",
  "linkedin",
  "facebook",
  "instagram",
  "twitter",
  "video_short",
];

export function isSocialFormat(f: string): f is SocialFormatKey {
  return (SOCIAL_FORMAT_KEYS as string[]).includes(f);
}

// ---------- shared helpers -------------------------------------------------

export function wordCount(s: string): number {
  const t = (s ?? "").trim();
  return t ? t.split(/\s+/).length : 0;
}

/** Truncate to at most `max` words, preferring to end on a sentence boundary. */
function truncateWords(s: string, max: number): string {
  const words = s.trim().split(/\s+/);
  if (words.length <= max) return s.trim();
  let out = words.slice(0, max).join(" ");
  // Back up to the last sentence end if one is reasonably close.
  const lastStop = Math.max(out.lastIndexOf(". "), out.lastIndexOf("! "), out.lastIndexOf("? "));
  if (lastStop > out.length * 0.5) out = out.slice(0, lastStop + 1);
  return out.trim();
}

const BANNED_OPENERS = [
  /^in today'?s (world|fast-paced|digital)/i,
  /^did you know/i,
  /\bis an important (issue|topic)\b/i,
];

/** True if the first line opens with a banned opener or a bare definition. */
export function hasBannedOpener(body: string): boolean {
  const first = (body ?? "").trim().split(/\n/)[0] ?? "";
  if (BANNED_OPENERS.some((re) => re.test(first))) return true;
  // "X is a legal ... that ..." definition-style opener.
  return /^[A-Z][\w\s]{2,40} is (a|an|the) (legal|type of|form of|process)/i.test(first);
}

/** True if the first line reads like one of the five approved hook formulas. */
export function looksLikeHook(body: string): boolean {
  const first = (body ?? "").trim().split(/\n/)[0]?.trim() ?? "";
  if (!first) return false;
  if (hasBannedOpener(body)) return false;
  const question = /\?\s*$/.test(first); // question hook
  const stat = /\b\d/.test(first.slice(0, 40)); // stat/number hook (leads with a number)
  // Direct-address / scenario hook: opens by speaking to the reader's situation.
  const directAddress = /^(if you|you|your|when you|after you|imagine|picture|ever )\b/i.test(first);
  const mythBust = /\b(most|many|everyone thinks|the myth|contrary to|myth)\b/i.test(first);
  return question || stat || directAddress || mythBust;
}

/**
 * NY / NJ must be spelled out (Rule 6). True if an abbreviated form is present.
 * Matches "NY", "N.Y.", "NYC", "NJ", "N.J." as standalone tokens; "New York"
 * and "New Jersey" spelled out do not trip it.
 */
export function hasStateAbbreviation(body: string): boolean {
  return /\b(N\.?Y\.?C?|N\.?J\.?)\b/.test(body ?? "");
}

/** Soft-CTA present and no hard-sell / guarantee language. */
export function hasSoftCta(body: string): boolean {
  const tail = (body ?? "").trim().slice(-280).toLowerCase();
  const invite =
    /(comment|dm|message us|reach out|let us know|learn more|learn your rights|read the full|talk it through|talk to|speak with|speak to|consultation|consult|conversation|contact|call us|call |we can help|we help|understand (your|whether|if)|for guidance|get guidance|clarify)/.test(
      tail,
    ) || /\?\s*$/.test(tail);
  const hardSell = /(guarantee|guaranteed|we will win|100%|act now|limited time|don'?t wait)/.test(tail);
  return invite && !hardSell;
}

// ---------- per-format caps ------------------------------------------------

export type CapSpec = {
  label: string;
  /** Instruction lines injected into the generator prompt for this format. */
  promptRules: string[];
  /** Violations against the hard caps ([] = passes). */
  validate: (body: string) => string[];
  /** Best-effort clamp to bring output within caps. */
  trim: (body: string) => string;
};

export const SOCIAL_CAPS: Record<SocialFormatKey, CapSpec> = {
  carousel: {
    label: "Instagram/LinkedIn carousel",
    promptRules: [
      "5 to 7 content slides, never more than 8 total including hook and CTA slides.",
      "Slide 1 is the hook: under 12 words.",
      "Each content slide body: 15 to 25 words maximum.",
      "Final slide is the CTA: one directive sentence under 15 words, include the phone number.",
      "Format each slide as 'Slide 1: ...' through 'Slide N: ...' on its own line, then a 'Caption:' line under 150 words with 3 to 5 hashtags.",
    ],
    validate: (body) => {
      const v: string[] = [];
      const { slides } = parseCarouselScript(body);
      if (slides.length < 5) v.push(`only ${slides.length} slides (need 5-7)`);
      if (slides.length > 8) v.push(`${slides.length} slides (max 8)`);
      const hook = slides[0];
      if (hook && wordCount(`${hook.headline} ${hook.sub}`) > 12)
        v.push("hook slide over 12 words");
      slides.slice(1, -1).forEach((s, i) => {
        const w = wordCount(`${s.headline} ${s.sub}`);
        if (w > 25) v.push(`content slide ${i + 2} over 25 words (${w})`);
      });
      return v;
    },
    trim: (body) => {
      // Clamp to the first 7 slides + caption; drop overflow slides.
      const lines = body.split(/\n/);
      let kept = 0;
      const out: string[] = [];
      for (const line of lines) {
        const isSlide = /^\s*(?:[-*•]\s*)?(?:\*\*)?slide\s*\d+/i.test(line);
        if (isSlide) {
          kept += 1;
          if (kept > 7) continue; // stop emitting further slide headers
        }
        if (kept <= 7 || /caption/i.test(line)) out.push(line);
      }
      return out.join("\n").trim();
    },
  },
  linkedin: {
    label: "LinkedIn post",
    promptRules: [
      "50 to 150 words total.",
      "Short paragraphs or single-line breaks, never dense blocks of text.",
      "One soft CTA at the end.",
    ],
    validate: (body) => {
      const w = wordCount(body);
      return w < 40 ? [`too short (${w} words)`] : w > 150 ? [`over 150 words (${w})`] : [];
    },
    trim: (body) => truncateWords(body, 150),
  },
  facebook: {
    label: "Facebook post",
    promptRules: [
      "50 to 120 words total.",
      "Slightly more casual tone than LinkedIn.",
      "One soft CTA at the end.",
    ],
    validate: (body) => {
      const w = wordCount(body);
      return w < 40 ? [`too short (${w} words)`] : w > 120 ? [`over 120 words (${w})`] : [];
    },
    trim: (body) => truncateWords(body, 120),
  },
  instagram: {
    label: "Instagram caption",
    promptRules: [
      "Hook line, then 2 to 4 short lines maximum.",
      "Hashtags listed separately at the bottom, not counted in caption length.",
    ],
    validate: (body) => {
      // Count non-empty lines that are not the hashtag block.
      const lines = body
        .split(/\n/)
        .map((l) => l.trim())
        .filter(Boolean)
        .filter((l) => !/^#/.test(l));
      return lines.length > 5 ? [`${lines.length} lines (hook + max 4)`] : [];
    },
    trim: (body) => {
      const hashtags = body.split(/\n/).filter((l) => /^\s*#/.test(l));
      const lines = body
        .split(/\n/)
        .map((l) => l.trim())
        .filter(Boolean)
        .filter((l) => !/^#/.test(l))
        .slice(0, 5);
      return [...lines, ...hashtags].join("\n").trim();
    },
  },
  twitter: {
    label: "X / Twitter thread",
    promptRules: [
      "4 to 6 tweets, each under 280 characters.",
      "Number each tweet '1/ 2/ 3/ ...'. Tweet 1 is the hook, the last tweet is the CTA.",
      "One idea per tweet.",
    ],
    validate: (body) => {
      const tweets = splitTweets(body);
      const v: string[] = [];
      if (tweets.length < 4) v.push(`only ${tweets.length} tweets (need 4-6)`);
      if (tweets.length > 6) v.push(`${tweets.length} tweets (max 6)`);
      tweets.forEach((t, i) => {
        if (t.length > 280) v.push(`tweet ${i + 1} over 280 chars (${t.length})`);
      });
      return v;
    },
    trim: (body) => {
      const tweets = splitTweets(body).slice(0, 6).map((t) => (t.length > 280 ? t.slice(0, 277) + "..." : t));
      return tweets.map((t, i) => (/^\d+\//.test(t) ? t : `${i + 1}/ ${t}`)).join("\n\n");
    },
  },
  video_short: {
    label: "TikTok / Reels script (Craig LeVay style)",
    promptRules: [
      "Strong one-line hook, then short punchy sentences with slight urgency.",
      "Minimal jargon, confident tone, no hype and no guarantees.",
      "Dual-audience framing when the topic allows (e.g. both employee and employer angles).",
      "75 to 110 words total — reads in 30 to 45 seconds spoken aloud.",
    ],
    validate: (body) => {
      const w = wordCount(body);
      return w < 60 ? [`too short (${w} words)`] : w > 120 ? [`over ~110 words (${w})`] : [];
    },
    trim: (body) => truncateWords(body, 110),
  },
};

/** Split a thread body into individual tweets by '1/'-style numbering or blank lines. */
function splitTweets(body: string): string[] {
  const text = (body ?? "").trim();
  if (!text) return [];
  // Prefer explicit "1/ ... 2/ ..." numbering.
  const numbered = text.split(/\n+(?=\s*\d+\s*\/)/).map((t) => t.trim()).filter(Boolean);
  if (numbered.length > 1) return numbered;
  // Fall back to blank-line separation.
  return text.split(/\n{2,}/).map((t) => t.trim()).filter(Boolean);
}

/** Validate a body against its format caps. */
export function validateSocial(format: SocialFormatKey, body: string): string[] {
  return SOCIAL_CAPS[format].validate(body);
}

/** Clamp a body to its format caps (best-effort floor). */
export function trimSocial(format: SocialFormatKey, body: string): string {
  return SOCIAL_CAPS[format].trim(body);
}
