/**
 * Emits the WordPress-ready HTML for the approved disclaimers.
 *
 *   node scripts/run.mjs scripts/emit-disclaimer-snippets.ts > disclaimers.html
 *
 * The wording lives in lib/legal-disclaimers.ts, which is also what
 * scripts/check-disclaimers.ts verifies the live site against. Generating the
 * markup from that module rather than writing it by hand is the point: hand-
 * copied legal text drifts from the text being checked for, and then the
 * checker passes on wording nobody approved.
 *
 * Classes are plain and prefixed so the theme can style them without a
 * specificity fight. No inline styles beyond the minimum, so the site's own CSS
 * governs the look.
 */
import {
  FOOTER_DISCLAIMER,
  RESULTS_VARY,
  AWARDS_NOTICE,
  AWARDS_METHODOLOGY_PATH,
  AWARDS_METHODOLOGY_INTRO,
  AWARD_METHODOLOGIES,
  DISCLAIMER_REVIEW_NOTES,
} from "@/lib/legal-disclaimers";

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const out: string[] = [];
const say = (s = "") => out.push(s);

say("<!-- ===================================================================");
say("     KATZ MELINGER - REQUIRED ADVERTISING DISCLAIMERS");
say("     Generated from lib/legal-disclaimers.ts. Do not edit this file by");
say("     hand: scripts/check-disclaimers.ts verifies the live site against");
say("     that module, so hand-edited wording will pass review and then fail");
say("     the check, or worse, pass the check while saying something nobody");
say("     approved.");
say("     =================================================================== -->");
say();

say("<!-- ---------------------------------------------------------------");
say("     1. SITE FOOTER - every page");
say("     Paste into the global footer template, not into individual pages.");
say("     --------------------------------------------------------------- -->");
say('<div class="km-legal-footer">');
for (const p of FOOTER_DISCLAIMER) say(`  <p>${esc(p)}</p>`);
say("</div>");
say();

say("<!-- ---------------------------------------------------------------");
say("     2. CASE RESULTS AND GOOGLE REVIEWS");
say("     Place directly beneath the result or the review block - RPC 7.1(d)");
say("     asks for prominent, and a footer three screens below the dollar");
say("     figure is the placement that gets criticised.");
say("     --------------------------------------------------------------- -->");
say(`<p class="km-results-vary">${esc(RESULTS_VARY)}</p>`);
say();

say("<!-- ---------------------------------------------------------------");
say("     3. AWARDS AND BADGES");
say("     Place beneath any award, ranking, or badge display.");
say("     --------------------------------------------------------------- -->");
const [firstSentence, ...restOfNotice] = AWARDS_NOTICE.split(". ");
const linkSentence = restOfNotice.join(". ");
const linkLabel = "Award Methodology Breakdown";
say('<p class="km-awards-notice">');
say(`  ${esc(firstSentence)}.`);
say(
  `  ${esc(linkSentence.replace(linkLabel, "|LINK|")).replace(
    "|LINK|",
    `<a href="${AWARDS_METHODOLOGY_PATH}">${linkLabel}</a>`,
  )}`,
);
say("</p>");
say();

say("<!-- ---------------------------------------------------------------");
say(`     4. THE METHODOLOGY PAGE ITSELF - create at ${AWARDS_METHODOLOGY_PATH}`);
say("     The notice above links here. Right now that URL is a 404.");
say("     --------------------------------------------------------------- -->");
say('<div class="km-award-methodology">');
say("  <h1>Awards, Honors, and Recognition Disclaimers</h1>");
for (const p of AWARDS_METHODOLOGY_INTRO) say(`  <p>${esc(p)}</p>`);
say("  <ul>");
for (const a of AWARD_METHODOLOGIES) {
  say("    <li>");
  const lead = a.publisher ? ` Published by ${esc(a.publisher)}.` : "";
  say(`      <strong>${esc(a.name)}:</strong>${lead}`);
  say(`      ${esc(a.basis)}`);
  say(
    `      View the full criteria on the <a href="${a.url}" target="_blank" rel="noopener noreferrer">${esc(a.linkText)}</a>.`,
  );
  say("    </li>");
}
say("  </ul>");
say("</div>");
say();

say("<!-- ===================================================================");
say("     BEFORE THIS GOES LIVE");
for (const n of DISCLAIMER_REVIEW_NOTES) {
  const wrapped = n.match(/.{1,66}(\s|$)/g) ?? [n];
  say(`       - ${wrapped[0].trim()}`);
  for (const w of wrapped.slice(1)) say(`         ${w.trim()}`);
}
say("     =================================================================== -->");

console.log(out.join("\n"));
