/**
 * Write supabase/content_known_traps_oct6.sql from lib/known-traps-oct6.ts.
 *
 *   node scripts/run.mjs scripts/emit-known-traps-oct6-sql.ts
 *
 * The TS file is the source; never edit the SQL by hand. Patterns go in as
 * dollar-quoted strings so no backslash or quote needs escaping.
 */
import { writeFileSync } from "node:fs";
import { OCT6_TRAPS } from "../lib/known-traps-oct6";

const q = (s: string | null | undefined) => (s == null ? "null" : `$t$${s}$t$`);
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(", ")}]::text[]` : "'{}'::text[]");

const rows = OCT6_TRAPS.map(
  (t) =>
    `  (${[
      "'00000000-0000-0000-0000-000000000001'",
      q(t.label),
      q(t.matchType),
      q(t.pattern),
      arr(t.unless),
      q(t.severity),
      q(`${t.note} (Oct 6 spec, trap ${t.number})`),
      "true",
      q(t.matchOn ?? null),
      t.caseSensitive ? "true" : "false",
      q(t.regexFlags ?? null),
      q(t.scope ?? null),
      q(t.appliesTo ?? "all"),
    ].join(", ")})`,
);

const sql = `-- ============================================================================
-- !! DB TARGET CHECK — read before running
-- ----------------------------------------------------------------------------
-- Run this against the LIVE marketing-SaaS Supabase project — the one your
-- active .env.local points at via NEXT_PUBLIC_SUPABASE_URL. Confirm the project
-- ref matches .env.local before you click Run. .env.local wins over any comment.
-- ============================================================================

-- ============================================================================
-- content_known_traps — Diana's Oct 6 2026 spec, Task 4 (engine + new traps)
-- GENERATED by scripts/emit-known-traps-oct6-sql.ts from lib/known-traps-oct6.ts.
-- Do not edit by hand; change the TS file and re-run the emitter.
-- Tested by: node scripts/run.mjs scripts/check-known-traps-oct6.ts
--
-- Engine columns (all optional; existing rows keep their behaviour):
--   match_on        null = whole draft with links stripped (the original
--                   behaviour), 'sentences', or 'raw_body'
--   case_sensitive  true = no "i" flag
--   regex_flags     extra RegExp flags ("u" for the emoji ranges)
--   scope           'title_or_keyword_contains:<text>'
--   applies_to      'all' or 'web' (blogs and web pages only; never social)
-- New match types: 'document' and 'document_missing'.
--
-- Idempotent: new rows insert on conflict (tenant_id, lower(label)) do nothing.
-- ============================================================================

begin;

alter table public.content_known_traps
  add column if not exists match_on       text,
  add column if not exists case_sensitive boolean not null default false,
  add column if not exists regex_flags    text,
  add column if not exists scope          text,
  add column if not exists applies_to     text not null default 'all';

alter table public.content_known_traps drop constraint if exists content_known_traps_match_type_check;
alter table public.content_known_traps add constraint content_known_traps_match_type_check
  check (match_type in ('phrase','regex','all_of','all_of_unless','document','document_missing'));

alter table public.content_known_traps drop constraint if exists content_known_traps_match_on_check;
alter table public.content_known_traps add constraint content_known_traps_match_on_check
  check (match_on is null or match_on in ('sentences','raw_body'));

alter table public.content_known_traps drop constraint if exists content_known_traps_applies_to_check;
alter table public.content_known_traps add constraint content_known_traps_applies_to_check
  check (applies_to in ('all','web'));

insert into public.content_known_traps
  (tenant_id, label, match_type, pattern, unless, severity, note, enabled,
   match_on, case_sensitive, regex_flags, scope, applies_to)
values
${rows.join(",\n")}
on conflict (tenant_id, lower(label)) do nothing;

commit;

-- Check: select label, match_type, match_on, applies_to from public.content_known_traps
--        where note like '%Oct 6 spec%' order by label;   -- expect ${OCT6_TRAPS.length} rows
`;

writeFileSync("supabase/content_known_traps_oct6.sql", sql);
console.log(`wrote supabase/content_known_traps_oct6.sql (${OCT6_TRAPS.length} traps)`);
