/**
 * Writes supabase/legal_statute_table.sql from lib/legal-statute-table.ts.
 *
 *   node scripts/run.mjs scripts/emit-statute-table-sql.ts
 *
 * One source for the table: edit the TypeScript (which the check script
 * tests), then regenerate. Never hand-edit the SQL.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { STATUTE_TABLE } from "../lib/legal-statute-table";

const TENANT = "00000000-0000-0000-0000-000000000001";
/** The last attorney review of this table. */
const REVIEWED = { by: "Kenneth Katz", at: "2026-09-30T00:00:00Z" };
const q = (s: string | null) => (s === null ? "null" : `'${s.replace(/'/g, "''")}'`);
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(", ")}]` : "'{}'::text[]");

const header = `-- ============================================================================
-- !! DB TARGET CHECK — read before running
-- ----------------------------------------------------------------------------
-- Run this against the LIVE marketing-SaaS Supabase project — the one your
-- active .env.local points at via NEXT_PUBLIC_SUPABASE_URL. Confirm the project
-- ref matches .env.local before you click Run. .env.local wins over any comment.
-- ============================================================================

-- ============================================================================
-- The statute table (Diana's Sept 28 spec, section 3 and Appendix A).
--
-- GENERATED by scripts/emit-statute-table-sql.ts from lib/legal-statute-table.ts.
-- Do not hand-edit: change the TypeScript, run scripts/check-statute-table.ts,
-- then regenerate.
--
-- ATTORNEY SIGN-OFF REQUIRED BEFORE RUNNING. Appendix A: "Before loading, an
-- attorney at the firm should initial this table."
--   Reviewed by: Kenneth Katz   Date: September 30, 2026 (all rows approved;
--   § 300 unless words and the OSHA 11(c) row added at review).
--
-- Until this runs, the statute check (lib/legal-statute-check.ts) does nothing.
-- Once it runs, a section cited for something it does not cover is a Critical
-- finding that holds approval, and a cited section not in this table is an
-- "unverified citation" for attorney review.
-- ============================================================================

create table if not exists public.legal_statute_table (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null,
  key             text not null,
  code            text not null,
  citation        text not null,
  aliases         text[] not null default '{}',
  covers          text not null,
  not_covers      text,
  mismatch_terms  text[] not null default '{}',
  unless_terms    text[] not null default '{}',
  source_url      text,
  enabled         boolean not null default true,
  reviewed_by     text,
  reviewed_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (tenant_id, key)
);

alter table public.legal_statute_table enable row level security;

drop policy if exists legal_statute_table_tenant on public.legal_statute_table;
create policy legal_statute_table_tenant on public.legal_statute_table
  for all
  using (tenant_id = public.current_tenant_id())
  with check (tenant_id = public.current_tenant_id());

`;

const rows = STATUTE_TABLE.map(
  (r) =>
    `  (${q(TENANT)}, ${q(r.key)}, ${q(r.code)}, ${q(r.citation)}, ${arr(r.aliases)},\n` +
    `   ${q(r.covers)},\n   ${q(r.notCovers)}, ${arr(r.mismatch)}, ${arr(r.unless)}, ${q(r.sourceUrl)})`,
).join(",\n");

const sql =
  header +
  `insert into public.legal_statute_table
  (tenant_id, key, code, citation, aliases, covers, not_covers, mismatch_terms, unless_terms, source_url)
values
${rows}
on conflict (tenant_id, key) do update set
  code = excluded.code,
  citation = excluded.citation,
  aliases = excluded.aliases,
  covers = excluded.covers,
  not_covers = excluded.not_covers,
  mismatch_terms = excluded.mismatch_terms,
  unless_terms = excluded.unless_terms,
  source_url = excluded.source_url,
  updated_at = now();

-- Attorney sign-off (Kenneth Katz, 2026-09-30). Rows added or changed after
-- that date need a new review: update REVIEWED below when they get one.
update public.legal_statute_table
   set reviewed_by = ${q(REVIEWED.by)}, reviewed_at = ${q(REVIEWED.at)}
 where tenant_id = ${q(TENANT)} and reviewed_at is null;
`;

const out = resolve(process.cwd(), "supabase/legal_statute_table.sql");
writeFileSync(out, sql);
console.log(`wrote ${STATUTE_TABLE.length} rows to ${out}`);
